### PR TITLE
Wicked game

### PR DESCRIPTION
**Pull request by BHamp**
I realized I don't have ruby installed on this computer, and didn't feel like bothering with it tonight so I haven't checked it out on this machine. I'll get it installed tomorrow so I can actually see how it looks going forward.

### CODE REVIEW

**Comment by spilth** [comment]
Thanks for working on this!

I went through it a few times and found a few minor nits on timing. I also adjusted the `order` attribute based on the current last song.

Let me know what you think of these adjustments:

```
@title=Wicked Game
@artist=Chris Isaak
@year=1989
@tempo=114
@key=B dorian
!difficulty=1
!spotify=https://open.spotify.com/track/7w5AOd6HrDIHewHfpABEss?si=ce04a482ab3942e8
!order=98

# Intro Riff

|--------------------------------| E
|----6b-7-0---6b-5---------------| B
|---4-------4-----7-6-4--2---1---| G
|-----------------------4---2----| D
|--------------------------------| A
|--------------------------------| E

# Intro Chords

| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |

# Verse 1

[Bm]The world was on fire and [A]no one could save me but [E]you
It's [Bm]strange what desire will [A]make foolish people [E]do
[Bm]I never dreamed that [A]I'd meet somebody like [E]you
And [Bm]I never dreamed that [A]I'd lose somebody like [E]you

# Chorus 1

No, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
No, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
With you [Bm] [A] [E]
With you [Bm] [A] [E](This world is only gonna break your heart)

# Verse 2

[Bm]What a wicked [A]game you play, [E]to make me feel this way
[Bm]What a wicked [A]thing to do, [E]to let me dream of you
[Bm]What a wicked [A]thing to say, [E]you never felt this way
[Bm]What a wicked [A]thing to do, [E]to make me dream of you

# Chorus 2

And, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
No, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
With you

# Intro Riff

| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |
| [Bm] | [A] | [E] | [E] |

# Verse 3

[Bm]The world was on fire and [A]no one could save me but [E]you
It's [Bm]strange what desire will [A]make foolish people [E]do
[Bm]I never dreamed that [A]I'd meet somebody like [E]you
And [Bm]I never dreamed that [A]I'd lose somebody like [E]you

# Chorus 3

No, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
No, [Bm]I [A]don't wanna fall in [E]love (this world is only gonna break your heart)
With you [Bm] [A] [E](This world is only gonna break your heart)
With you [Bm] [A] [E](This world is only gonna break your heart)
No, [Bm]I [A] [E](this world is only gonna break your heart)
[Bm] [A] [E](This world is only gonna break your heart)

# Outro

[Bm]Nobody
[A]loves no one
[E]
```

**Comment by spilth** [comment]
This also has me considering if I should have an `contributor` attribute to give people credit for their contributions 🤔

**Comment by BHamp** [comment]
Yeah, I definitely agree with these changes. I wasn't sure how picky we wanted to be with timing

**Comment by spilth** [comment]
Weird - I don't know why switching from using `master` to use `main` will close this branch/branch 😕

**Pull request closed without merging**
